<script setup>
import { ref } from 'vue'
import { MapPin, ChevronDown, Filter, Layers3, RefreshCw, Download, ArrowUpRight, CircleHelp } from 'lucide-vue-next'
const graphNodes=ref([
{id:'gx',label:'广西',type:'region',x:265,y:125},{id:'vn',label:'越南',type:'region',x:180,y:270},{id:'id',label:'印尼',type:'region',x:315,y:400},{id:'th',label:'泰国',type:'region',x:625,y:110},{id:'my',label:'马来西亚',type:'region',x:720,y:235},{id:'la',label:'老挝',type:'region',x:625,y:405},{id:'mn',label:'锰矿',type:'resource',x:340,y:75},{id:'sn',label:'锡矿',type:'resource',x:540,y:72},{id:'core',label:'矿产资源',sub:'协同网络',type:'core',x:450,y:250}])
const graphEdges=[['core','gx'],['core','vn'],['core','id'],['core','th'],['core','my'],['core','la'],['gx','vn'],['gx','mn'],['th','my'],['th','sn'],['vn','id'],['my','la'],['id','la'],['sn','th'],['mn','gx']]
const graphCanvas=ref(null),draggingGraphNode=ref(null),selectedGraphNode=ref(null)
const moveGraphNode=(event)=>{if(!draggingGraphNode.value||!graphCanvas.value)return;const svg=graphCanvas.value.querySelector('svg'),point=svg.createSVGPoint();point.x=event.clientX;point.y=event.clientY;const position=point.matrixTransform(svg.getScreenCTM().inverse());const node=graphNodes.value.find(item=>item.id===draggingGraphNode.value);if(node){const radius=node.type==='core'?38:node.type==='region'?27:23;node.x=Math.max(radius+5,Math.min(895-radius,position.x));node.y=Math.max(radius+5,Math.min(505-radius,position.y))}}
const endGraphDrag=()=>{draggingGraphNode.value=null}
</script>
<template>
          <div class="graph-toolbar panel"><div class="graph-filters"><button class="filter-select"><MapPin :size="14"/>广西及东盟 <ChevronDown :size="13"/></button><button class="filter-select"><Layers3 :size="14"/>全部资源类型 <ChevronDown :size="13"/></button><button class="filter-select"><Filter :size="14"/>关系筛选 <ChevronDown :size="13"/></button></div><div class="graph-actions"><span class="graph-count">146 个实体 <i>·</i> 218 条关系</span><button class="icon-btn"><RefreshCw :size="15"/></button><button class="button secondary"><Download :size="14"/>导出图谱</button></div></div>
          <section class="panel knowledge-graph"><div class="kg-title"><div><h2>广西与东盟矿产资源关系网络</h2><p>拖动节点可调整关系布局 · 区域分布、资源禀赋与产业协作 · 案例数据</p></div><div class="graph-zoom"><button>−</button><span>100%</span><button>+</button></div></div><div class="graph-canvas interactive-graph" ref="graphCanvas" @pointermove="moveGraphNode" @pointerup="endGraphDrag" @pointercancel="endGraphDrag"><svg viewBox="0 0 900 510" role="img" aria-label="可拖动的广西与东盟矿产资源知识图谱"><g class="graph-links"><line v-for="(edge,i) in graphEdges" :key="i" :x1="graphNodes.find(n=>n.id===edge[0]).x" :y1="graphNodes.find(n=>n.id===edge[0]).y" :x2="graphNodes.find(n=>n.id===edge[1]).x" :y2="graphNodes.find(n=>n.id===edge[1]).y"/></g><g v-for="node in graphNodes" :key="node.id" class="graph-node" :class="[node.type,{dragging:draggingGraphNode===node.id,focused:selectedGraphNode===node.id}]" :transform="`translate(${node.x} ${node.y})`" @pointerdown.stop.prevent="draggingGraphNode=node.id; selectedGraphNode=node.id; $event.currentTarget.setPointerCapture($event.pointerId)" @click="selectedGraphNode=node.id"><circle :r="node.type==='core'?38:node.type==='region'?27:23"/><text class="node-label" y="4">{{node.label}}</text><text v-if="node.sub" class="node-sub" y="18">{{node.sub}}</text></g></svg></div><div class="kg-legend"><span><i class="legend-node green"></i>国家 / 地区</span><span><i class="legend-node gray"></i>矿产资源</span><span><i class="legend-node amber"></i>产业需求</span><span><i class="legend-edge"></i>资源分布</span><span><i class="legend-edge dashed"></i>潜在供需关系</span><span class="legend-hint"><CircleHelp :size="13"/>拖动节点调整关系图</span></div></section>
          <div class="graph-bottom"><section class="panel entity-panel"><div class="panel-heading"><div><h2>重点区域资源</h2><p>基于公开资料整理</p></div><button class="text-button">查看全部 <ArrowUpRight :size="13"/></button></div><div class="entity-list"><div><span class="entity-country">广西</span><span>锰、铝土、锡、锑、稀土</span><small>资源分布 · 自治区自然资源厅</small></div><div><span class="entity-country">印度尼西亚</span><span>镍、锡、铝土、铜</span><small>矿产生产 · USGS 2025</small></div><div><span class="entity-country">越南</span><span>铝土、稀土、钛铁矿</span><small>区域资源 · ASEAN 研究</small></div></div></section><section class="panel relation-panel"><div class="panel-heading"><div><h2>关系类型</h2><p>知识库中的关系构成</p></div></div><div class="relation-bars"><div><span>位于 / 分布于</span><b>94</b><i><u style="width:78%"></u></i></div><div><span>供应 / 需求</span><b>62</b><i><u style="width:54%"></u></i></div><div><span>加工 / 应用</span><b>38</b><i><u style="width:33%"></u></i></div><div><span>合作 / 贸易</span><b>24</b><i><u style="width:22%"></u></i></div></div></section></div>
          <div class="source-note">资源实体依据公开资料整理；图谱关系、企业需求和供需连线为演示案例，不代表实时交易或官方储量统计。来源：<a href="https://dnr.gxzf.gov.cn/kpyd/kpyd/t16025036.shtml" target="_blank" rel="noreferrer">广西壮族自治区自然资源厅</a>、<a href="https://www.usgs.gov/centers/national-minerals-information-center/indonesia" target="_blank" rel="noreferrer">USGS 印度尼西亚矿产摘要</a>。</div>
</template>
