<script setup>
import { defineEmits } from 'vue'
import { Layers3, ArrowUpRight, Network, Handshake, Activity, FileSearch, Check, Pickaxe, MoreHorizontal, ExternalLink } from 'lucide-vue-next'
const emit=defineEmits(['navigate'])
</script>
<template>
          <div class="overview-grid">
            <section class="panel metric-card"><div class="metric-top"><span>已收录资源实体</span><span class="metric-icon"><Layers3 :size="16"/></span></div><div class="metric-value">1,284<span class="metric-unit">条</span></div><div class="metric-foot"><span class="trend up"><ArrowUpRight :size="13"/>12.8%</span><span>较上月</span><span class="foot-muted">覆盖 11 个国家和地区</span></div><div class="sparkline"><svg viewBox="0 0 180 38"><path d="M0 32 C18 28 21 20 38 24 S61 11 77 18 S99 23 115 12 S140 20 151 7 S170 10 180 2" fill="none" stroke="#4c8b72" stroke-width="2"/></svg></div></section>
            <section class="panel metric-card"><div class="metric-top"><span>有效知识关系</span><span class="metric-icon blue"><Network :size="16"/></span></div><div class="metric-value">3,672<span class="metric-unit">条</span></div><div class="metric-foot"><span class="trend up"><ArrowUpRight :size="13"/>8.4%</span><span>较上月</span><span class="foot-muted">实体关系已完成消歧</span></div><div class="sparkline"><svg viewBox="0 0 180 38"><path d="M0 30 C20 22 24 29 39 18 S61 22 79 11 S103 17 119 8 S143 16 157 4 S170 8 180 1" fill="none" stroke="#6487a6" stroke-width="2"/></svg></div></section>
            <section class="panel metric-card"><div class="metric-top"><span>待匹配合作机会</span><span class="metric-icon amber"><Handshake :size="16"/></span></div><div class="metric-value">86<span class="metric-unit">项</span></div><div class="metric-foot"><span class="trend neutral"><Activity :size="13"/>持续更新</span><span class="foot-muted">基于 42 家案例企业需求</span></div><div class="sparkline"><svg viewBox="0 0 180 38"><path d="M0 31 C19 30 24 15 40 22 S60 13 75 20 S98 9 113 15 S136 8 150 12 S169 3 180 5" fill="none" stroke="#bc9253" stroke-width="2"/></svg></div></section>
            <section class="panel metric-card"><div class="metric-top"><span>语料处理任务</span><span class="metric-icon violet"><FileSearch :size="16"/></span></div><div class="metric-value">12<span class="metric-unit">个</span></div><div class="metric-foot"><span class="trend up"><Check :size="13"/>全部完成</span><span class="foot-muted">最近一次处理 09:42</span></div><div class="sparkline"><svg viewBox="0 0 180 38"><path d="M0 30 C18 28 23 19 40 24 S61 14 78 16 S100 10 115 15 S139 5 154 11 S169 2 180 3" fill="none" stroke="#8d79a6" stroke-width="2"/></svg></div></section>
          </div>
          <div class="dashboard-grid"><section class="panel graph-panel"><div class="panel-heading"><div><h2>区域资源关系</h2><p>资源实体与区域分布 · 案例数据</p></div><button class="text-button" @click="emit('navigate', '多模态知识图谱','知识图谱')">查看知识图谱 <ArrowUpRight :size="14"/></button></div><div class="mini-graph"><svg viewBox="0 0 700 245" aria-label="广西东盟资源关系图"><g stroke="#d8e2df" stroke-width="1.4"><path d="M350 121 180 60M350 121 143 155M350 121 245 210M350 121 520 55M350 121 568 140M350 121 483 207M180 60 143 155M520 55 568 140M245 210 483 207M180 60 270 35M520 55 425 30"/></g><g fill="#f4f8f6" stroke="#97b2a7" stroke-width="1.4"><circle cx="350" cy="121" r="42"/><circle cx="180" cy="60" r="30"/><circle cx="143" cy="155" r="27"/><circle cx="245" cy="210" r="28"/><circle cx="520" cy="55" r="30"/><circle cx="568" cy="140" r="27"/><circle cx="483" cy="207" r="28"/><circle cx="270" cy="35" r="23"/><circle cx="425" cy="30" r="23"/></g><g fill="#39554b" font-size="11" text-anchor="middle" font-family="sans-serif"><text x="350" y="118">区域资源</text><text x="350" y="134">关系网络</text><text x="180" y="64">广西</text><text x="143" y="159">越南</text><text x="245" y="214">印尼</text><text x="520" y="59">泰国</text><text x="568" y="144">马来西亚</text><text x="483" y="211">老挝</text><text x="270" y="39">锰</text><text x="425" y="34">锡</text></g></svg></div><div class="graph-legend"><span><i class="legend-node green"></i>区域</span><span><i class="legend-node gray"></i>矿产资源</span><span><i class="legend-line"></i>供需与分布关系</span><span class="legend-note">示意关系，可展开查看</span></div></section>
            <section class="panel opportunity-panel"><div class="panel-heading"><div><h2>供需合作线索</h2><p>近期识别的匹配机会</p></div><button class="icon-btn"><MoreHorizontal :size="18"/></button></div><div class="opportunity-list"><div class="opp-row"><div class="opp-icon"><Pickaxe :size="16"/></div><div class="opp-info"><strong>高纯锰矿 · 南宁新能源材料</strong><span>广西崇左市 · 需求匹配度高</span></div><span class="match-score">92<span>%</span></span></div><div class="opp-row"><div class="opp-icon blue-bg"><Pickaxe :size="16"/></div><div class="opp-info"><strong>铝土矿 · 广西铝业科技</strong><span>广西百色市 · 供需信息互补</span></div><span class="match-score">87<span>%</span></span></div><div class="opp-row"><div class="opp-icon amber-bg"><Pickaxe :size="16"/></div><div class="opp-info"><strong>镍矿 · 柳州动力电池材料</strong><span>印尼苏拉威西 · 跨境供应线索</span></div><span class="match-score">81<span>%</span></span></div><div class="opp-row"><div class="opp-icon violet-bg"><Pickaxe :size="16"/></div><div class="opp-info"><strong>钾盐 · 桂海绿色矿业</strong><span>老挝甘蒙省 · 项目合作线索</span></div><span class="match-score">76<span>%</span></span></div></div><button class="full-link" @click="emit('navigate', '双向智能匹配','供需智能对接')">进入供需智能对接 <ArrowUpRight :size="14"/></button></section></div>
          <div class="lower-grid"><section class="panel table-panel"><div class="panel-heading"><div><h2>最近语料处理</h2><p>抽取、向量化与结果消解任务</p></div><button class="text-button" @click="emit('navigate', '多模态语料接入','语料抽取')">查看全部 <ArrowUpRight :size="14"/></button></div><div class="table-wrap"><table><thead><tr><th>任务名称</th><th>语料来源</th><th>处理类型</th><th>完成时间</th><th>状态</th></tr></thead><tbody><tr><td><span class="file-chip"><FileSearch :size="14"/>东盟关键矿产资料集</span></td><td>公开报告 · 18 份</td><td>抽取 + 消歧</td><td>今天 09:42</td><td><span class="badge success"><i></i>已完成</span></td></tr><tr><td><span class="file-chip"><FileSearch :size="14"/>广西矿产资源分布资料</span></td><td>政务公开 · 12 份</td><td>实体关系抽取</td><td>今天 09:18</td><td><span class="badge success"><i></i>已完成</span></td></tr><tr><td><span class="file-chip"><FileSearch :size="14"/>企业需求案例语料</span></td><td>演示案例 · 42 条</td><td>语义解析</td><td>昨天 16:30</td><td><span class="badge success"><i></i>已完成</span></td></tr></tbody></table></div></section><section class="panel distribution-panel"><div class="panel-heading"><div><h2>资源类别分布</h2><p>当前知识库中的主要实体</p></div><button class="icon-btn"><MoreHorizontal :size="18"/></button></div><div class="dist-list"><div class="dist-row"><span>有色金属</span><div class="dist-track"><i style="width:82%"></i></div><b>328</b></div><div class="dist-row"><span>能源矿产</span><div class="dist-track"><i style="width:64%"></i></div><b>256</b></div><div class="dist-row"><span>稀土与稀有金属</span><div class="dist-track"><i style="width:48%"></i></div><b>192</b></div><div class="dist-row"><span>非金属矿产</span><div class="dist-track"><i style="width:35%"></i></div><b>141</b></div><div class="dist-row"><span>其他资源</span><div class="dist-track"><i style="width:22%"></i></div><b>86</b></div></div></section></div>
          <div class="source-note">数据说明：页面资源类型参考广西壮族自治区自然资源厅公开资料与 ASEAN / USGS 矿产信息；企业、需求、匹配结果及统计数值为演示数据，便于后续接入真实业务数据。 <a href="https://dnr.gxzf.gov.cn/kpyd/kpyd/t16025036.shtml" target="_blank" rel="noreferrer">广西矿产资源 <ExternalLink :size="11"/></a><a href="https://asean.org/wp-content/uploads/2024/01/ASEAN-IGF-Scoping-Study-on-Critical-Minerals-Supply-Chains-in-ASEAN-final.pdf" target="_blank" rel="noreferrer">ASEAN 关键矿产研究 <ExternalLink :size="11"/></a></div>
</template>
