<script setup>
import { computed, defineEmits } from 'vue'
import { Layers3, ArrowUpRight, Network, Handshake, Activity, FileSearch, Check, Pickaxe, MoreHorizontal, ExternalLink } from 'lucide-vue-next'
import graphSnapshot from '../../public/data/guangxi-asean-knowledge-graph.json'
const emit=defineEmits(['navigate'])
const overviewGraph = computed(() => {
  const countries = graphSnapshot.nodes.filter(node => node.type === 'region' && node.id.startsWith('asean-'))
  const central = graphSnapshot.nodes.find(node => node.id === 'region-guangxi')
  const countryById = new Map(countries.map(node => [node.id, node]))
  const memberEdges = graphSnapshot.edges.filter(edge => edge.from === 'region-asean' && countryById.has(edge.to))
  const hierarchyRelations = new Set(['下辖一级行政区','划分规划区'])
  const locationRelations = new Set(['企业所在地 / 项目地','产区 / 分布关联','资源分布于'])
  const regionEntities = new Map()
  countries.forEach(country => {
    const descendants = new Set([country.id])
    for (let depth = 0; depth < 3; depth += 1) graphSnapshot.edges.forEach(edge => {
      if (hierarchyRelations.has(edge.type) && descendants.has(edge.from)) descendants.add(edge.to)
    })
    const relevantEntities = new Set(descendants)
    graphSnapshot.edges.forEach(edge => { if (locationRelations.has(edge.type) && descendants.has(edge.from)) relevantEntities.add(edge.to) })
    graphSnapshot.edges.forEach(edge => {
      if (!relevantEntities.has(edge.from)) return
      const resource = graphSnapshot.nodes.find(node => node.id === edge.to && node.type === 'resource')
      if (resource) regionEntities.set(`${country.id}:${resource.id}`, { regionId: country.id, resourceId: resource.id })
    })
  })
  const resourceNodes = [...new Set([...regionEntities.values()].map(link => link.resourceId))]
    .map(id => graphSnapshot.nodes.find(node => node.id === id)).filter(Boolean).slice(0, 6)
  const guangxiAsean = graphSnapshot.edges.find(edge => edge.from === central?.id && edge.to === 'region-asean')
  return { central, countries, memberEdges, guangxiAsean, resourceNodes, regionEntities: [...regionEntities.values()].filter(link => resourceNodes.some(node => node.id === link.resourceId)) }
})
const countryPositions = [
  {x:60,y:32},{x:155,y:32},{x:250,y:32},{x:350,y:32},{x:450,y:32},{x:545,y:32},{x:640,y:32},
  {x:100,y:190},{x:225,y:190},{x:475,y:190},{x:600,y:190},
]
const positionedCountries = computed(() => overviewGraph.value.countries.map((node,index)=>({...node,...countryPositions[index%countryPositions.length]})))
const positionedResources = computed(() => overviewGraph.value.resourceNodes.map((node,index)=>({...node,x:102+index*99,y:258,lines:Array.from(node.label).length>7?[Array.from(node.label).slice(0,Math.ceil(Array.from(node.label).length/2)).join(''),Array.from(node.label).slice(Math.ceil(Array.from(node.label).length/2)).join('')]:[node.label]})))
</script>
<template>
          <div class="overview-grid">
            <section class="panel metric-card"><div class="metric-top"><span>已收录资源实体</span><span class="metric-icon"><Layers3 :size="16"/></span></div><div class="metric-value">1,284<span class="metric-unit">条</span></div><div class="metric-foot"><span class="trend up"><ArrowUpRight :size="13"/>12.8%</span><span>较上月</span><span class="foot-muted">覆盖 11 个国家和地区</span></div><div class="sparkline"><svg viewBox="0 0 180 38"><path d="M0 32 C18 28 21 20 38 24 S61 11 77 18 S99 23 115 12 S140 20 151 7 S170 10 180 2" fill="none" stroke="#4c8b72" stroke-width="2"/></svg></div></section>
            <section class="panel metric-card"><div class="metric-top"><span>有效知识关系</span><span class="metric-icon blue"><Network :size="16"/></span></div><div class="metric-value">3,672<span class="metric-unit">条</span></div><div class="metric-foot"><span class="trend up"><ArrowUpRight :size="13"/>8.4%</span><span>较上月</span><span class="foot-muted">实体关系已完成消歧</span></div><div class="sparkline"><svg viewBox="0 0 180 38"><path d="M0 30 C20 22 24 29 39 18 S61 22 79 11 S103 17 119 8 S143 16 157 4 S170 8 180 1" fill="none" stroke="#6487a6" stroke-width="2"/></svg></div></section>
            <section class="panel metric-card"><div class="metric-top"><span>待匹配合作机会</span><span class="metric-icon amber"><Handshake :size="16"/></span></div><div class="metric-value">86<span class="metric-unit">项</span></div><div class="metric-foot"><span class="trend neutral"><Activity :size="13"/>持续更新</span><span class="foot-muted">覆盖 42 家企业需求</span></div><div class="sparkline"><svg viewBox="0 0 180 38"><path d="M0 31 C19 30 24 15 40 22 S60 13 75 20 S98 9 113 15 S136 8 150 12 S169 3 180 5" fill="none" stroke="#bc9253" stroke-width="2"/></svg></div></section>
            <section class="panel metric-card"><div class="metric-top"><span>语料处理任务</span><span class="metric-icon violet"><FileSearch :size="16"/></span></div><div class="metric-value">12<span class="metric-unit">个</span></div><div class="metric-foot"><span class="trend up"><Check :size="13"/>全部完成</span><span class="foot-muted">最近一次处理 09:42</span></div><div class="sparkline"><svg viewBox="0 0 180 38"><path d="M0 30 C18 28 23 19 40 24 S61 14 78 16 S100 10 115 15 S139 5 154 11 S169 2 180 3" fill="none" stroke="#8d79a6" stroke-width="2"/></svg></div></section>
          </div>
          <div class="dashboard-grid"><section class="panel graph-panel"><div class="panel-heading"><div><h2>区域资源关系</h2><p>与多模态知识图谱同源 · 国家级概览</p></div><button class="text-button" @click="emit('navigate', '多模态知识图谱','知识图谱')">查看知识图谱 <ArrowUpRight :size="14"/></button></div><div class="mini-graph overview-network"><svg viewBox="0 0 700 310" aria-label="广西东盟国家级资源关系图"><defs><linearGradient id="overview-link" x1="0" x2="1"><stop stop-color="#1d4ed8" stop-opacity=".72"/><stop offset="1" stop-color="#38bdf8" stop-opacity=".5"/></linearGradient></defs><g class="overview-links"><line v-for="edge in overviewGraph.memberEdges" :key="edge.to" x1="350" y1="111" :x2="positionedCountries.find(node=>node.id===edge.to)?.x" :y2="positionedCountries.find(node=>node.id===edge.to)?.y"/><line v-if="overviewGraph.guangxiAsean" x1="350" y1="111" x2="350" y2="176" class="resource-link"/><line v-for="link in overviewGraph.regionEntities" :key="`${link.regionId}-${link.resourceId}`" :x1="positionedCountries.find(node=>node.id===link.regionId)?.x" :y1="positionedCountries.find(node=>node.id===link.regionId)?.y" :x2="positionedResources.find(node=>node.id===link.resourceId)?.x" :y2="positionedResources.find(node=>node.id===link.resourceId)?.y" class="resource-link"/></g><g class="overview-country" v-for="node in positionedCountries" :key="node.id" :transform="`translate(${node.x} ${node.y})`"><circle r="20"/><text y="4">{{node.label}}</text></g><g class="overview-resource" v-for="node in positionedResources" :key="node.id" :transform="`translate(${node.x} ${node.y})`"><rect x="-45" y="-19" width="90" height="38" rx="10"/><text v-for="(line,index) in node.lines" :key="index" x="0" :y="node.lines.length===1?4:(index===0?-2:10)">{{line}}</text></g><g class="overview-center"><circle cx="350" cy="111" r="28"/><text x="350" y="108">东盟</text><text x="350" y="122" class="center-sub">11 个成员国</text></g><g class="overview-guangxi"><circle cx="350" cy="176" r="17"/><text x="350" y="180">广西</text></g></svg></div><div class="graph-legend"><span><i class="legend-node green"></i>广西与东盟国家</span><span><i class="legend-node gray"></i>图谱资源实体</span><span><i class="legend-line"></i>成员与资源分布关系</span><span class="legend-note">11 个国家 · 同步真实图谱</span></div></section>
            <section class="panel opportunity-panel"><div class="panel-heading"><div><h2>供需合作线索</h2><p>近期识别的匹配机会</p></div><button class="text-button" @click="emit('navigate', '双向智能匹配','供需智能对接')">查看全部 <ArrowUpRight :size="14"/></button></div><div class="opportunity-list"><div class="opp-row"><div class="opp-icon"><Pickaxe :size="16"/></div><div class="opp-info"><strong>高纯锰矿 · 南宁新能源材料</strong><span>广西崇左市 · 需求匹配度高</span></div><span class="match-score">92<span>%</span></span></div><div class="opp-row"><div class="opp-icon blue-bg"><Pickaxe :size="16"/></div><div class="opp-info"><strong>铝土矿 · 广西铝业科技</strong><span>广西百色市 · 供需信息互补</span></div><span class="match-score">87<span>%</span></span></div><div class="opp-row"><div class="opp-icon amber-bg"><Pickaxe :size="16"/></div><div class="opp-info"><strong>镍矿 · 柳州动力电池材料</strong><span>印尼苏拉威西 · 跨境供应线索</span></div><span class="match-score">81<span>%</span></span></div><div class="opp-row"><div class="opp-icon violet-bg"><Pickaxe :size="16"/></div><div class="opp-info"><strong>钾盐 · 桂海绿色矿业</strong><span>老挝甘蒙省 · 项目合作线索</span></div><span class="match-score">76<span>%</span></span></div></div><button class="full-link" @click="emit('navigate', '双向智能匹配','供需智能对接')">进入供需智能对接 <ArrowUpRight :size="14"/></button></section></div>
          <div class="lower-grid"><section class="panel table-panel"><div class="panel-heading"><div><h2>最近语料处理</h2><p>抽取、向量化与结果消解任务</p></div><button class="text-button" @click="emit('navigate', '多模态语料接入','语料抽取')">查看全部 <ArrowUpRight :size="14"/></button></div><div class="table-wrap"><table><thead><tr><th>任务名称</th><th>语料来源</th><th>处理类型</th><th>完成时间</th><th>状态</th></tr></thead><tbody><tr><td><span class="file-chip"><FileSearch :size="14"/>东盟关键矿产资料集</span></td><td>公开报告 · 18 份</td><td>抽取 + 消歧</td><td>今天 09:42</td><td><span class="badge success"><i></i>已完成</span></td></tr><tr><td><span class="file-chip"><FileSearch :size="14"/>广西矿产资源分布资料</span></td><td>政务公开 · 12 份</td><td>实体关系抽取</td><td>今天 09:18</td><td><span class="badge success"><i></i>已完成</span></td></tr><tr><td><span class="file-chip"><FileSearch :size="14"/>企业需求语料</span></td><td>企业需求 · 42 条</td><td>语义解析</td><td>昨天 16:30</td><td><span class="badge success"><i></i>已完成</span></td></tr></tbody></table></div></section><section class="panel distribution-panel"><div class="panel-heading"><div><h2>资源类别分布</h2><p>当前知识库中的主要实体</p></div><button class="text-button" @click="emit('navigate', '东盟资源库','资源管理')">东盟资源库 <ArrowUpRight :size="14"/></button></div><div class="dist-list"><div class="dist-row"><span>有色金属</span><div class="dist-track"><i style="width:82%"></i></div><b>328</b></div><div class="dist-row"><span>能源矿产</span><div class="dist-track"><i style="width:64%"></i></div><b>256</b></div><div class="dist-row"><span>稀土与稀有金属</span><div class="dist-track"><i style="width:48%"></i></div><b>192</b></div><div class="dist-row"><span>非金属矿产</span><div class="dist-track"><i style="width:35%"></i></div><b>141</b></div><div class="dist-row"><span>其他资源</span><div class="dist-track"><i style="width:22%"></i></div><b>86</b></div></div></section></div>
          
</template>

