<script setup>
import { computed, ref } from 'vue'
import { Mountain, Database, FileSearch, Network, Map, Search, Handshake, Settings, ChevronDown, ChevronRight, Bell, CircleHelp, PanelLeftClose, LayoutDashboard, Play, MapPin, MoreHorizontal, Activity } from 'lucide-vue-next'
import OverviewPage from './components/OverviewPage.vue'
import CorpusPage from './components/CorpusPage.vue'
import KnowledgeGraphPage from './components/KnowledgeGraphPage.vue'
import MatchingPage from './components/MatchingPage.vue'
import PlaceholderPage from './components/PlaceholderPage.vue'
const active=ref('概览'),expanded=ref('供需智能对接')
const navGroups=[
{name:'资源管理',icon:Database,children:['矿产资源目录','资源信息录入','资源信息审核']},{name:'语料抽取',icon:FileSearch,children:['多模态语料接入','构建向量知识库','抽取结果消解']},{name:'知识图谱',icon:Network,children:['多模态知识图谱','知识融合与补全']},{name:'资源分布监测',icon:Activity,children:['区域空间概况','供需分布监测','缺失数据管理']},{name:'地图可视化',icon:Map,children:['资源分布图','供需热力图','资源禀赋分析']},{name:'资源查询',icon:Search,children:['资源目录查询','图谱关系查询']},{name:'供需智能对接',icon:Handshake,children:['需求语义解析','双向智能匹配','潜在合作方推荐']},{name:'系统管理',icon:Settings,children:['用户与权限','操作日志','系统设置']}]
const setPage=(page,group)=>{active.value=page;if(group)expanded.value=group}
const isMatching=computed(()=>['需求语义解析','双向智能匹配','潜在合作方推荐'].includes(active.value))
const isCorpus=computed(()=>['多模态语料接入','构建向量知识库','抽取结果消解'].includes(active.value))
const isGraph=computed(()=>['多模态知识图谱','知识融合与补全'].includes(active.value))
const isOverview=computed(()=>active.value==='概览')
const activeTitle=computed(()=>active.value)
const pageDescription=computed(()=>isOverview.value?'整合区域资源语料，构建可追溯的知识关系与供需协作网络。':isCorpus.value?'从公开资料与业务文档中提取实体关系，沉淀为可检索的资源知识。':isGraph.value?'浏览广西与东盟国家的矿产资源、区域与产业需求关系。':isMatching.value?'解析企业需求，发现跨区域资源供需与潜在合作机会。':'查看广西及东盟各国资源信息与业务动态。')
</script>
<template>
<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark"><Mountain :size="21"/></div><div><strong>桂东盟资源协同</strong><span>RESOURCE INTELLIGENCE</span></div><button class="icon-btn collapse"><PanelLeftClose :size="16"/></button></div><button class="workspace"><span class="workspace-dot"></span><span>广西 · 东盟资源工作台</span><ChevronDown :size="14"/></button><div class="nav-caption">工作空间</div><nav><button class="nav-item" :class="{selected:isOverview}" @click="setPage('概览')"><LayoutDashboard :size="17"/><span>概览</span></button><template v-for="group in navGroups" :key="group.name"><button class="nav-item" :class="{groupactive:expanded===group.name}" @click="expanded=expanded===group.name?'':group.name"><component :is="group.icon" :size="17"/><span>{{group.name}}</span><ChevronDown class="nav-chevron" :class="{turned:expanded===group.name}" :size="14"/></button><div v-if="expanded===group.name" class="subnav"><button v-for="child in group.children" :key="child" class="subnav-item" :class="{selected:active===child}" @click="setPage(child,group.name)"><span class="subnav-dot"></span>{{child}}</button></div></template></nav><div class="sidebar-bottom"><div class="data-status"><span class="status-dot"></span><span>案例数据模式</span><span class="status-right">DEMO</span></div><div class="sidebar-user"><div class="avatar small">林</div><div><strong>林予安</strong><span>平台管理员</span></div><MoreHorizontal :size="18"/></div></div></aside>
<main class="main-area"><header class="topbar"><div class="crumb"><span>工作空间</span><ChevronRight :size="13"/><strong>{{activeTitle}}</strong></div><div class="top-actions"><span class="region-pill"><MapPin :size="14"/>广西 · 东盟</span><button class="icon-btn top-icon"><CircleHelp :size="18"/></button><button class="icon-btn top-icon notification"><Bell :size="18"/><i></i></button><div class="top-divider"></div><div class="user-info"><div class="avatar">林</div><div><strong>林予安</strong><span>平台管理员</span></div><ChevronDown :size="14"/></div></div></header><div class="content-scroll"><div class="page-heading"><div><div class="eyebrow">广西 · 东盟自然资源协同平台</div><h1>{{isOverview?'资源要素，连接区域合作':activeTitle}}</h1><p>{{pageDescription}}</p></div><div class="heading-actions"><span class="sync-label"><span class="status-dot"></span>案例数据已就绪</span><button class="button secondary" @click="setPage('资源目录查询','资源查询')"><Search :size="15"/>资源查询</button><button class="button primary" @click="setPage('多模态语料接入','语料抽取')"><Play :size="14"/>开始处理</button></div></div><OverviewPage v-if="isOverview" @navigate="setPage"/><CorpusPage v-else-if="isCorpus"/><KnowledgeGraphPage v-else-if="isGraph"/><MatchingPage v-else-if="isMatching" :initial-view="active" @navigate="setPage"/><PlaceholderPage v-else :title="active" @navigate="setPage"/><footer class="page-footer"><span>桂东盟资源协同平台 <i>·</i> 竞赛原型</span><span>数据更新于 2026-10-08 <i>·</i> 仅供案例演示</span></footer></div></main></div>
</template>
