<script setup>
import { computed, ref } from 'vue'
import { Mountain, Database, FileSearch, Network, Map, Search, Handshake, Settings, ChevronDown, ChevronRight, Bell, CircleHelp, PanelLeftClose, LayoutDashboard, MapPin, MoreHorizontal, Activity } from 'lucide-vue-next'
import OverviewPage from './components/OverviewPage.vue'
import ResourceLibraryPage from './components/ResourceLibraryPage.vue'
import CorpusIntakePage from './components/CorpusIntakePage.vue'
import VectorKnowledgePage from './components/VectorKnowledgePage.vue'
import CorpusResolutionPage from './components/CorpusResolutionPage.vue'
import KnowledgeGraphPage from './components/KnowledgeGraphPage.vue'
import KnowledgeFusionPage from './components/KnowledgeFusionPage.vue'
import MatchingPage from './components/MatchingPage.vue'
import ResourceUploadPage from './components/ResourceUploadPage.vue'
import PlaceholderPage from './components/PlaceholderPage.vue'
import MapDistributionPage from './components/MapDistributionPage.vue'
import ResourceAskPage from './components/ResourceAskPage.vue'
const active=ref('概览'),expanded=ref('供需智能对接')
const navGroups=[
{name:'资源管理',icon:Database,children:['东盟资源库','资源信息录入',/*'资源信息审核'*/]},{name:'语料抽取',icon:FileSearch,children:['多模态语料接入','构建向量知识库','抽取结果消解']},{name:'知识图谱',icon:Network,children:['多模态知识图谱','知识融合与补全']},{name:'资源分布监测',icon:Activity,children:['区域空间概况','供需分布监测','缺失数据管理']},{name:'地图可视化',icon:Map,children:['资源分布图','供需热力图','资源禀赋分析']},{name:'资源查询',icon:Search,children:['资源需求智能问答','资源目录查询','图谱关系查询']},{name:'供需智能对接',icon:Handshake,children:['需求语义解析','双向智能匹配','潜在合作方推荐']},{name:'系统管理',icon:Settings,children:['用户与权限','操作日志','系统设置']}]
const setPage=(page,group)=>{active.value=page;if(group)expanded.value=group}
const isMatching=computed(()=>['需求语义解析','双向智能匹配','潜在合作方推荐','企业供需知识图谱'].includes(active.value))
const isCorpus=computed(()=>['多模态语料接入','构建向量知识库','抽取结果消解'].includes(active.value))
const isGraph=computed(()=>['多模态知识图谱','知识融合与补全'].includes(active.value))
const isOverview=computed(()=>active.value==='概览')
const isLibrary=computed(()=>active.value==='东盟资源库')
const isMap=computed(()=>active.value==='资源分布图')
const isAsk=computed(()=>active.value==='资源需求智能问答')
const activeTitle=computed(()=>active.value)
const pageDescription=computed(()=>isOverview.value?'整合区域资源语料，构建可追溯的知识关系与供需协作网络。':isLibrary.value?'总览东盟多语种语料资源的库容、贡献分布与最新动态。':active.value==='资源信息录入'?'录入语料资源信息并上传附件，自动估算容量、校验名称查重。':isCorpus.value?'从公开资料与业务文档中提取实体关系，沉淀为可检索的资源知识。':active.value==='知识融合与补全'?'发现图谱缺口，检索语料证据并推断候选实体关系。':isGraph.value?'浏览广西与东盟国家的矿产资源、区域与产业需求关系。':isMatching.value?'解析企业需求，发现跨区域资源供需与潜在合作机会。':isAsk.value?'描述你的企业或需求，自动匹配广西与东盟的矿产与自然资源需求线索。':'查看广西及东盟各国资源信息与业务动态。')
</script>
<template>
<<<<<<< HEAD
<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark"><Mountain :size="21"/></div><div><strong>桂东盟资源协同</strong><span>RESOURCE INTELLIGENCE</span></div><button class="icon-btn collapse"><PanelLeftClose :size="16"/></button></div><button class="workspace"><span class="workspace-dot"></span><span>广西 · 东盟资源工作台</span><ChevronDown :size="14"/></button><div class="nav-caption">工作空间</div><nav><button class="nav-item" :class="{selected:isOverview}" @click="setPage('概览')"><LayoutDashboard :size="17"/><span>概览</span></button><template v-for="group in navGroups" :key="group.name"><button class="nav-item" :class="{groupactive:expanded===group.name}" @click="expanded=expanded===group.name?'':group.name"><component :is="group.icon" :size="17"/><span>{{group.name}}</span><ChevronDown class="nav-chevron" :class="{turned:expanded===group.name}" :size="14"/></button><div v-if="expanded===group.name" class="subnav"><button v-for="child in group.children" :key="child" class="subnav-item" :class="{selected:active===child}" @click="setPage(child,group.name)"><span class="subnav-dot"></span>{{child}}</button></div></template></nav><div class="sidebar-bottom"><div class="sidebar-user"><div class="avatar small">管</div><div><strong>管理员</strong><span>平台管理员</span></div><MoreHorizontal :size="18"/></div></div></aside>
<main class="main-area"><header class="topbar"><div class="crumb"><span>工作空间</span><ChevronRight :size="13"/><strong>{{activeTitle}}</strong></div><div class="top-actions"><span class="region-pill"><MapPin :size="14"/>广西 · 东盟</span><button class="icon-btn top-icon"><CircleHelp :size="18"/></button><button class="icon-btn top-icon notification"><Bell :size="18"/><i></i></button><div class="top-divider"></div><div class="user-info"><div class="avatar">管</div><div><strong>管理员</strong><span>平台管理员</span></div><ChevronDown :size="14"/></div></div></header><div class="content-scroll"><div class="page-heading"><div><h1>{{isOverview?'资源要素，连接区域合作':activeTitle}}</h1><p>{{pageDescription}}</p></div></div><OverviewPage v-if="isOverview" @navigate="setPage"/><CorpusIntakePage v-else-if="active==='多模态语料接入'"/><VectorKnowledgePage v-else-if="active==='构建向量知识库'"/><CorpusResolutionPage v-else-if="active==='抽取结果消解'"/><KnowledgeGraphPage v-else-if="active==='多模态知识图谱'" :title="active"/><KnowledgeFusionPage v-else-if="active==='知识融合与补全'"/><MatchingPage v-else-if="isMatching" :initial-view="active" @navigate="setPage"/><PlaceholderPage v-else :title="active" @navigate="setPage"/></div></main></div>
=======
<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark"><Mountain :size="21"/></div><div><strong>桂东盟资源协同</strong><span>RESOURCE INTELLIGENCE</span></div><button class="icon-btn collapse"><PanelLeftClose :size="16"/></button></div><button class="workspace"><span class="workspace-dot"></span><span>广西 · 东盟资源工作台</span><ChevronDown :size="14"/></button><div class="nav-caption">工作空间</div><nav><button class="nav-item" :class="{selected:isOverview}" @click="setPage('概览')"><LayoutDashboard :size="17"/><span>概览</span></button><template v-for="group in navGroups" :key="group.name"><button class="nav-item" :class="{groupactive:expanded===group.name}" @click="expanded=expanded===group.name?'':group.name"><component :is="group.icon" :size="17"/><span>{{group.name}}</span><ChevronDown class="nav-chevron" :class="{turned:expanded===group.name}" :size="14"/></button><div v-if="expanded===group.name" class="subnav"><button v-for="child in group.children" :key="child" class="subnav-item" :class="{selected:active===child}" @click="setPage(child,group.name)"><span class="subnav-dot"></span>{{child}}</button></div></template></nav><div class="sidebar-bottom"><div class="sidebar-user"><div class="avatar small">林</div><div><strong>林予安</strong><span>平台管理员</span></div><MoreHorizontal :size="18"/></div></div></aside>
<main class="main-area"><header class="topbar"><div class="crumb"><span>工作空间</span><ChevronRight :size="13"/><strong>{{activeTitle}}</strong></div><div class="top-actions"><span class="region-pill"><MapPin :size="14"/>广西 · 东盟</span><button class="icon-btn top-icon"><CircleHelp :size="18"/></button><button class="icon-btn top-icon notification"><Bell :size="18"/><i></i></button><div class="top-divider"></div><div class="user-info"><div class="avatar">林</div><div><strong>林予安</strong><span>平台管理员</span></div><ChevronDown :size="14"/></div></div></header><div class="content-scroll"><div class="page-heading"><div><h1>{{isOverview?'资源要素，连接区域合作':activeTitle}}</h1><p>{{pageDescription}}</p></div></div><OverviewPage v-if="isOverview" @navigate="setPage"/><ResourceLibraryPage v-else-if="isLibrary"/><CorpusIntakePage v-else-if="active==='多模态语料接入'"/><VectorKnowledgePage v-else-if="active==='构建向量知识库'"/><CorpusResolutionPage v-else-if="active==='抽取结果消解'"/><ResourceUploadPage v-else-if="active==='资源信息录入'"/><KnowledgeGraphPage v-else-if="active==='多模态知识图谱'" :title="active"/><KnowledgeFusionPage v-else-if="active==='知识融合与补全'"/><MatchingPage v-else-if="isMatching" :initial-view="active" @navigate="setPage"/><ResourceAskPage v-else-if="isAsk"/><MapDistributionPage v-else-if="isMap"/><PlaceholderPage v-else :title="active" @navigate="setPage"/></div></main></div>
>>>>>>> 47f10b169155c030977df26bfa509bb4da79d24b
</template>
